### ISSUE TITLE
Any chance we could get an updated version?

### ISSUE THREAD

**Issue by GAMERGOD2636** [Lew29/The-Finals-Anti-Recoil#8]
As I'm sure you already know, the finals recently had an update that added some new weapons. Which brings me back to my question: could we get an update? No rush at all if so. I was just curious.

**Comment by jarcnpink** [comment]
would like to know as well.

**Comment by Lew29** [comment]
@GAMERGOD2636 @jarcnpink I don't play the finals anymore and stopped updating the script because of reports of it being detected. Have you both still managed to continue playing without any issues of being banned?

If so, then I'm open to updating my game to incorporate the new weapons. However, if there's still a risk of detection and bans, it might not be worth the effort.

**Comment by GAMERGOD2636** [comment]
I don't know if the individual program is detected or not. I _do however_ believe that someone else on github is using it (or something very similar) in a program that I currently use. So far, that program is still undetected. If you'd like to reach out to him, here's the specific project: https://github.com/IceyFL/The-Finals-AI-Cheat

I'm confident that you two will be able to pull it off. If you do, thanks in advance!

**Comment by KOSOVALI12** [comment]
I play myself, it is not detected with the software you made

**Comment by jarcnpink** [comment]
@Lew29 I already have 370 hours of gameplay and haven't been detected, so if you're free, please update the data on the new weapons.

**Comment by Lew29** [comment]
@GAMERGOD2636 @jarcnpink @KOSOVALI12 I added the new guns, I didn't realise they were both burst it only took like 5 minutes.
[The-Finals-Anti-Recoil-V3.0.zip](https://github.com/Lew29/The-Finals-Anti-Recoil/files/14628312/The-Finals-Anti-Recoil-V3.0.zip)
